#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 100.
# It displays FizzBuzz when the number is a multiple of 3 and 5
# It displays Fizz when the number is multiple of 3
# It displays Buzz when the number is a multiple of 5

for i in {1..100}; do 
    modulo_3=$((i%3))
    modulo_5=$((i%5))


    if [[ $modulo_3 -eq 0 && $modulo_5 -eq 0 ]]; then 
        echo "FizzBuzz"
    elif [[ $modulo_3 -eq 0 ]]; then 
        echo "Fizz"
    elif [[ $modulo_5 -eq 0 ]]; then 
        echo "Buzz"
    else
        echo "$i"
    fi

done