#!/bin/bash
# This bash script displays the content of the file /etc/passwd


while read p; do
    user=$(cut -d ':' -f 1)
    id=$(cut -d ':' -f 3)
    dir_path=$(rev | cut -d ':' -f 2 | rev)

    echo "$user:$id:$dir_path"
done < /etc/passwd