#!/usr/bin/env bash
# This Bash script displays Best School 10 times, but for the 9th iteration, it displays Best School and then Hi on a new line.

i=0
while [ $i -lt 10 ]; do 
    echo "Best School"

    if [ $i == 9 ]; then 
        echo "Hi"
    fi

    ((i+=1))
done