#!/usr/bin/env bash
# This Bash script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=1

while [ $hour -le 12 ]; do 
    minute=0

    while [ $minute -lt 60 ]; do 
        if [ $minute -eq 0 ]; then 
            echo "Hour: $hour"
            ((hour+=1))
        else
            echo "$minute"
        fi

        ((minute+=1))
    done
done