#!/usr/bin/env bash
# This Bash script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in .; do
    cut -d "-" -f 2
done