#!/usr/bin/env bash
# This Bash script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

dir=$(pwd)
for file in $dir; do
    result=$(cut -d "-" -f 2)
    echo $result
done