#!/usr/bin/env bash
# This Bash script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

mkdir -p /var/run/
touch /var/run/myscript.pid

the_world_is_flat=true

# handle_sigterm() {
#     echo "I hate the kill command"
#     exit 0
# }

# handle_sigint() {
#     echo "Y U no love me?!"
#     exit 0
# }

# handle_sigquit_sigterm() {
#     rm -r /var/run/myscript.pid 
#     pkill -f "10-process_and_pid_file"
#     exit 0
# }

# trap handle_sigterm,handle_sigquit_sigterm SIGTERM
# trap handle_sigquit_sigterm SIGQUIT
# trap handle_sigint SIGINT

trap 'echo "I hate the kill command" && rm -r /var/run/myscript.pid && pkill -f "10-process_and_pid_file"' SIGTERM
trap 'rm -r /var/run/myscript.pid && pkill -f "10-process_and_pid_file"' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while [ $the_world_is_flat ]; do
    echo 'To infinity and beyond'
done