#!/usr/bin/env bash
# This Bash script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/my_process.pid"

case "$1" in
	"start") 
        ./manage_my_process &
	    echo "$!" > "$file"

        echo "manage_my_process started"
		;;
	"stop") 
		pkill -f "./manage_my_process"
	    rm $file

        echo "manage_my_process stopped"
		;;
	"restart") 
		pkill -f "./manage_my_process"
        rm $file

        ./manage_my_process &
	    echo "$!" > "$file"

        echo "manage_my_process restarted"
		;;
	*) 
        echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac