#!/usr/bin/env bash
# This Bash script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

mkdir -p /var/run/
touch /var/run/myscript.pid

the_world_is_flat=true

while [ $the_world_is_flat ]; do
    echo 'To infinity and beyond'
done